### ISSUE TITLE
strange ApiVersionError.UPDATE_TO_NEWER_VERSION

### ISSUE THREAD

**Issue by pacuna** [googleads/google-api-ads-ruby#124]
I started to get this error a couple of days ago when fetching all the LICA's. I'm using the newest API and gem versions.

My code is pretty similar to the one in the examples:

```
    lica_service = @dfp.service(:LineItemCreativeAssociationService, :v201702)
    statement = DfpApi::FilterStatement.new

    loop do
      page = lica_service.get_line_item_creative_associations_by_statement(statement.toStatement)
      break if statement.offset > page[:total_result_set_size]
      if page[:results]
        page[:results].each_with_index do |lica, index|
          puts "#{index + statement.offset} Creative with ID #{lica[:creative_id]} was found."
        end
      end
      statement.offset += DfpApi::SUGGESTED_PAGE_LIMIT
    end
```

The weird thing is that it fails after fetching a lot of LICA's:

```
...
13492 Creative with ID 105998528428 was found.
13493 Creative with ID 105998530228 was found.
13494 Creative with ID 105998531548 was found.
13495 Creative with ID 105998532748 was found.
13496 Creative with ID 105998614948 was found.
13497 Creative with ID 105998618188 was found.
13498 Creative with ID 105998629468 was found.
13499 Creative with ID 105998633428 was found.
DfpApi::V201702::LineItemCreativeAssociationService::ApiException: [ApiVersionError.UPDATE_TO_NEWER_VERSION @ ]
	from /usr/local/rvm/gems/ruby-2.3.1/gems/google-ads-common-0.12.6/lib/ads_common/savon_service.rb:123:in `handle_errors'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/google-ads-common-0.12.6/lib/ads_common/savon_service.rb:92:in `execute_action'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/google-dfp-api-0.20.0/lib/dfp_api/v201702/line_item_creative_association_service.rb:29:in `get_line_item_creative_associations_by_statement'
	from /home/app/webapp/app/services/creatives_service.rb:13:in `block in get_all_creatives'
	from /home/app/webapp/app/services/creatives_service.rb:12:in `loop'
	from /home/app/webapp/app/services/creatives_service.rb:12:in `get_all_creatives'
	from (irb):3
	from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

And it always fails in the same batch. Like I said, I started to get the error just a few days ago. I run a cron task every day to fetch that data and now it's failing.
What could be happening?

Thanks in advance.

**Comment by christopherseeley** [comment]
There's an issue with DFP where certain creatives are inaccessible via the API. There's a fix in the works - you can follow the thread on the API forum for updates:
https://groups.google.com/forum/#!topic/google-doubleclick-for-publishers-api/qG1hPzw7RnU
