### ISSUE TITLE
run_saved_query': undefined local variable or method `response' for main:Object (NameError) 

### ISSUE THREAD

**Issue by octadv** [googleads/google-api-ads-ruby#155]
Hi
I'm getting an error when i use the report service/ run_saved_query.rb

`I, [2018-05-11T11:48:34.618427 #9291]  INFO -- : ID: 21633779192, URL: https://ads.google.com/apis/ads/publisher/v201802/ReportService, Service: ReportService, Action: get_saved_queries_by_statement, Response time: 134ms, Request ID: 38f82175a501e977198e6fb7d755b8e4, Is fault: false
dfp.rb:39:in `run_saved_query': undefined local variable or method `response' for main:Object (NameError)
Did you mean?  respond_to?
	from dfp.rb:82:in `<main>'
(api) dev@data:~$`

**Comment by donovanfm** [comment]
It looks like there's a variable reference error in this example. Thanks for bringing it to our attention. [Line 39](https://github.com/googleads/google-api-ads-ruby/blob/master/dfp_api/examples/v201802/report_service/run_saved_query.rb#L39) should be changed from ```saved_query = response[:results].first``` to ```saved_query = saved_query_page[:results].first```.

My apologies for this oversight. We have a release next week, and I'll be sure to update this example in the new library version. For now, you can make the change in your local environment, and that should be all that's needed to get the example working.
