### ISSUE TITLE
YAML Boolean Values

### ISSUE THREAD

**Issue by Lewis-Clayton** [googleads/google-api-ads-ruby#59]
Just updated to the latest version (google-adwords-api (0.15.2)) to get support for AdWords v201506 and now I'm getting the following error when using `download_report_as_file`

```
API_VERSION = :v201506
adwords_api  = AdwordsApi::Api.new(CONFIG_FILE)
report_utils = adwords_api.report_utils(API_VERSION)
report_definition = {:selector=>{:fields=>["CampaignId", "AccountCurrencyCode", "CampaignName"], :date_range=>{:min=>"20150701", :max=>"20150701"}}, :report_name=>"CAMPAIGN_PERFORMANCE_REPORT", :report_type=>"CAMPAIGN_PERFORMANCE_REPORT", :download_format=>"CSV", :date_range_type=>"CUSTOM_DATE", :include_zero_impressions=>"true"}
report_utils.download_report_as_file(report_definition, file_name, account_cid)

NoMethodError: undefined method `strip' for true:TrueClass
  from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/header.rb:17:in `block in initialize_http_header'
  from /usr/local/var/rbenv/versions/2.2.2/gemsets/xxx/gems/rack-1.6.4/lib/rack/utils.rb:490:in `block in each'
  from /usr/local/var/rbenv/versions/2.2.2/gemsets/xxx/gems/rack-1.6.4/lib/rack/utils.rb:489:in `each'
  from /usr/local/var/rbenv/versions/2.2.2/gemsets/xxx/gems/rack-1.6.4/lib/rack/utils.rb:489:in `each'
  from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/header.rb:15:in `initialize_http_header'
  from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:43:in `initialize'
  from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http/request.rb:14:in `initialize'
  from /usr/local/var/rbenv/versions/2.2.2/gemsets/xxx/gems/httpi-1.1.1/lib/httpi/adapter/net_http.rb:102:in `new'
  from /usr/local/var/rbenv/versions/2.2.2/gemsets/xxx/gems/httpi-1.1.1/lib/httpi/adapter/net_http.rb:102:in `request_client'
  from /usr/local/var/rbenv/versions/2.2.2/gemsets/xxx/gems/httpi-1.1.1/lib/httpi/adapter/net_http.rb:76:in `block in do_request'
  from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:853:in `start'
  from /usr/local/var/rbenv/versions/2.2.2/gemsets/xxx/gems/httpi-1.1.1/lib/httpi/adapter/net_http.rb:75:in `do_request'
  from /usr/local/var/rbenv/versions/2.2.2/gemsets/xxx/gems/httpi-1.1.1/lib/httpi/adapter/net_http.rb:30:in `post'
  from /usr/local/var/rbenv/versions/2.2.2/gemsets/xxx/gems/httpi-1.1.1/lib/httpi.rb:96:in `block in post'
  from /usr/local/var/rbenv/versions/2.2.2/gemsets/xxx/gems/httpi-1.1.1/lib/httpi.rb:193:in `with_adapter'
  from /usr/local/var/rbenv/versions/2.2.2/gemsets/xxx/gems/httpi-1.1.1/lib/httpi.rb:94:in `post'
  from /usr/local/var/rbenv/versions/2.2.2/gemsets/xxx/gems/google-ads-common-0.9.9/lib/ads_common/http.rb:52:in `post_response'
  from /usr/local/var/rbenv/versions/2.2.2/gemsets/xxx/gems/google-adwords-api-0.15.2/lib/adwords_api/report_utils.rb:155:in `make_adhoc_request'
  from /usr/local/var/rbenv/versions/2.2.2/gemsets/xxx/gems/google-adwords-api-0.15.2/lib/adwords_api/report_utils.rb:139:in `get_report_response'
  from /usr/local/var/rbenv/versions/2.2.2/gemsets/xxx/gems/google-adwords-api-0.15.2/lib/adwords_api/report_utils.rb:57:in `download_report'
  from /usr/local/var/rbenv/versions/2.2.2/gemsets/xxx/gems/google-adwords-api-0.15.2/lib/adwords_api/report_utils.rb:76:in `download_report_as_file'

```

It seems to be tripping up with my CONFIG_FILE on "skip_report_header".

```
....truncated
:library:
  :log_level: INFO
  :skip_report_header: true
  :skip_report_summary: true
  :skip_column_header: false
```

Changing to strings fixed the issue for me.

```
:library:
  :log_level: INFO
  :skip_report_header: 'true'
  :skip_report_summary: 'true'
  :skip_column_header: 'false'
```

I raise this here as this is breaking behaviour from the previous version.

Regards,

Lewis

**Comment by mcloonan** [comment]
Thanks for the report. I'll look into this.

**Comment by mcloonan** [comment]
This was fixed in the latest release.
