### ISSUE TITLE
ConversionTrackerService#get does not handle NaN

### ISSUE THREAD

**Issue by adstage-david** [googleads/google-api-ads-ruby#77]
When I make a request for a list of conversion trackers on account id (6800061575) with the following request info:

```
{:fields=>["AlwaysUseDefaultRevenueValue", "AppId", "AppPlatform", "AppPostbackUrl", "BackgroundColor", "Category", "ConversionPageLanguage", "ConversionValue", "CountingType", "DefaultRevenueCurrencyCode", "DefaultRevenueValue", "ExcludeFromBidding", "Id
", "IsProductAdsChargeable", "MarkupLanguage", "Name", "NumConversionEvents", "NumConvertedClicks", "ProductAdsChargeableConversionWindow", "Status", "TextFormat", "TrackingCodeType", "ViewthroughLookbackWindow"], :predicates=>[{:field=>"Status", :operator=>"IN", :values=>["ENABLED", "DISABLED", "HIDDEN"]}], :paging=>{:start_index=>0, :number_results=>500}}
```

I get an error thrown within the normalizer code:

```
ArgumentError: invalid value for Float(): "NaN"
    [  0] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:235:in `Float'",
    [  1] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:235:in `normalize_item'",
    [  2] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:98:in `normalize_output_field'",
    [  3] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:77:in `block in normalize_fields'",
    [  4] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:73:in `each'",
    [  5] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:73:in `normalize_fields'",
    [  6] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:128:in `normalize_hash_field'",
    [  7] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:96:in `normalize_output_field'",
    [  8] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:112:in `block in normalize_array_field'",
    [  9] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:112:in `map'",
    [ 10] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:112:in `normalize_array_field'",
    [ 11] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:94:in `normalize_output_field'",
    [ 12] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:77:in `block in normalize_fields'",
    [ 13] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:73:in `each'",
    [ 14] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:73:in `normalize_fields'",
    [ 15] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:148:in `normalize_hash_field'",
    [ 16] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:96:in `normalize_output_field'",
    [ 17] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:77:in `block in normalize_fields'",
    [ 18] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:73:in `each'",
    [ 19] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:73:in `normalize_fields'",
    [ 20] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:67:in `normalize_output'",
    [ 21] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/results_extractor.rb:41:in `extract_result'",
    [ 22] "/app/vendor/bundle/ruby/2.1.0/gems/google-ads-common-0.9.9/lib/ads_common/savon_service.rb:85:in `execute_action'",
    [ 23] "/app/vendor/bundle/ruby/2.1.0/gems/google-adwords-api-0.15.2/lib/adwords_api/v201506/conversion_tracker_service.rb:21:in `get'",
```

The conversion in question looks like this, including the NaN value for "defaultRevenueValue":

```
<entries xmlns:xsi="http://www.w3.org/2001/XMLS
chema-instance" xsi:type="AdWordsConversionTracker"><id>180679886</id><name>wertwertw</name><status>ENABLED</status><category>DEFAULT</category><viewthroughLookbackWindow>30</viewthroughLookbackWindow><isProductAdsChargeable>false</isProductAdsChargeable>
<productAdsChargeableConversionWindow>30</productAdsChargeableConversionWindow><ctcLookbackWindow>30</ctcLookbackWindow><countingType>MANY_PER_CLICK</countingType><defaultRevenueValue>NaN</defaultRevenueValue>...
```

Originally reported in this thread - where I was directed to report it here instead. Apparently NaN is a valid value that needs to be handled better by the extractor.

https://groups.google.com/forum/#!topic/adwords-api/-H_Wc6LADxk

**Comment by mcloonan** [comment]
I'm not sure if this actually a valid response from the API or not, but the plan is to make sure that this error doesn't prevent all the valid results from being returned in the event that this happens.

**Comment by mcloonan** [comment]
The API no longer returns NaN values here, so I'm going to close this out.
